### PR TITLE
HFX-1842: backport CP-17631 for Dundee

### PR DESCRIPTION
**Pull request by zli**

### CODE REVIEW

**Review by lindig — COMMENTED** [review]
This is a backport of https://github.com/xapi-project/xenopsd/pull/272 and I believe it is faithful.

**Review by lindig — APPROVED** [review]

**Comment by Frezzle** [comment]
The original changes included a new `-vgt_monitor_config_file` option: https://github.com/xapi-project/xenopsd/pull/272/files#diff-7a8f9b276e7662a150bdc8e87d9de515R1538

Why is this not included in the backport?

**Comment by zli** [comment]
The vgt option probably doesn't exist in Dundee.  In the original patch, this flags exists in the source code before the change, but this is not the case in the Dundee version. I can see certain adaption was needed for the previous Cream backport as well.

**Comment by Frezzle** [comment]
@zli Ah, I see - searching around a bit more it was added into master around the Dundee release, so probably didn't make it into Dundee as you said: https://github.com/xapi-project/xen-api/pull/2665. In that case, everything looks good to me. Merging.

**Review by Frezzle — APPROVED** [review]

**Pull request merged**
